### ISSUE TITLE
Using Function-try inside an ArrayedCollection.do loop corrupts interpreter

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1428]
Here's the original example from in a Quark method.

It did return nil, but after that chaos breaks out and 'add' is called on the symbol 'init'

```
going to make
I'm having an error
ERROR: Arduino not found
value of q: nil
returning q: nil
   nil
what it returned: nil
ERROR: Message 'add' not understood.
RECEIVER:
   Symbol 'init'
ARGS:
   nil
CALL STACK:
	DoesNotUnderstandError:reportError   0x1110f3a58
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x1110ad048
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x1110ad468
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x111060d78
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x110f658f8
		arg this = 'init'
		arg selector = 'add'
		arg args = [*1]
	ArrayedCollection:do   0x1111a2b48
		arg this = [*1]
		arg function = <instance of Function>
		var i = 0
	Collection:collectAs   0x113b21b48
		arg this = [*1]
		arg function = <instance of Function>
		arg class = <instance of Meta_Array>
		var res = [*0]
	Quark:dependencies   0x115e69058
		arg this = <instance of Quark>
		var deps = [*1]
	Meta_Quarks:installQuark   0x11417e658
		arg this = <instance of Meta_Quarks>
		arg quark = <instance of Quark>
		var deps = nil
		var incompatible = <instance of Function>
		var prev = nil
	Meta_Quarks:install   0x1145ab648
		arg this = <instance of Meta_Quarks>
		arg name = "SWMiniBee"
		arg refspec = nil
		var path = nil
		var quark = <instance of Quark>
	Interpreter:interpretPrintCmdLine   0x1146185e8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Quarks.install("SWMiniBee")
"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x1136b6b48
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'add' not understood.
RECEIVER: init
```

---
ignore this

here is an attempt to isolate the bug in non-class code, but I made a mistake and there is a missing ; as the comments below point out:

```supercollider
a = {
  var q;
  {
    q= \ouch.dontDoThis;
  }.try({ arg err;
    q.debug("in handler");
  });
  q.debug("after handler")
}

// "special byte codes inserted by compiler for this method"
["Ardunio"].do({ arg name;
  a.value(name)
})

```

Even though the error is handled and completed, the do loop call stack is infected.

what happens next is that selectors are called on objects that are adjacent in memory. it could be anything

```
ERROR: Message 'at' not understood.
RECEIVER:
Instance of Function {    (0x1148b1398, gc=58, fmt=00, flg=00, set=02)
  instance variables [2]
    def : instance of FunctionDef - closed
    context : Frame (0x10b789098) of Interpreter:functionCompileContext
}
ARGS:
Instance of String {    (0x1148bae68, gc=58, fmt=07, flg=10, set=02)
  indexed slots [7]
      0 : A
      1 : r
      2 : d
      3 : u
      4 : n
      5 : i
      6 : o
}
CALL STACK:
	DoesNotUnderstandError:reportError   0x109c55668
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x109c5cff8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x10b3c71a8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x109c59b28
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x109c5ff38
		arg this = <instance of Function>
		arg selector = 'at'
		arg args = [*1]
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine   0x114a37768
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "a = {
	var q;
   {
	 q= \ouc..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x109c06058
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'at' not understood.
RECEIVER: a Function
```

**Comment by jamshark70** [comment]
I tried repeatedly to reproduce this in Linux (current master), but I don't see the problem. That's unfortunate and troubling.

I *have* seen problems in the past with Object:getBackTrace, with symptoms very similar to the issue here: methods getting called on completely unpredictable receivers. At one point, it became such a problem for me that I implemented a private extension that skips the `getBackTrace` in Exception:new (for cases where I was using `try` to swallow errors, and I was never going to post the stack trace).

Felix, could you try this? If the problem goes away, then we would know that the problem is in getBackTrace. My gut says this is it.

    + Function {
    	tryNoTrace { arg handler;
    		var result = this.prTryNoTrace;
    		if (result.isException) { ^handler.value(result); }
    			{ ^result }
    	}
    	prTryNoTrace {
    		var result, thread = thisThread;
    		var next = thread.exceptionHandler,
    			wasInProtectedFunc = Exception.inProtectedFunction;
    		thread.exceptionHandler = {|error|
    			thread.exceptionHandler = next; // pop
    			^error
    		};
    		Exception.inProtectedFunction = false;
    		result = this.value;
    		Exception.inProtectedFunction = wasInProtectedFunc;
    		thread.exceptionHandler = next; // pop
    		^result
    	}
    }

**Comment by crucialfelix** [comment]
thanks, I'll try that one.

could somebody else also run my example and see if it bombs for them ?  I've also seen gray count errors recently, so something else may be corrupted.

**Comment by nuss** [comment]
I can reproduce the error on my machine (Ubuntu Studio 14.04) if I execute *the whole* block of code *at once*. I do not get an error if I execute the function definition in 'a' and the 'do' block separately.

**Comment by jamshark70** [comment]
There is a semicolon missing between `a = {}` and `["Arduino"]`. If I execute the whole block without the semicolon, I get an error. If I add the missing semicolon, then I again can't reproduce the problem.

**Comment by crucialfelix** [comment]
ah damn, that missing ; does explain the example posted.

but the 2nd stacktrace was from compiled class code. I've already done a work around for that.

this commit would still have the bug: https://github.com/crucialfelix/supercollider/commit/84d1c1bf4983911569bb14ea84225eca22770929

you can see the class at that point in time:

https://github.com/crucialfelix/supercollider/blob/84d1c1bf4983911569bb14ea84225eca22770929/SCClassLibrary/Common/Quarks/Quark.sc

the (deliberately thrown) error is caught in *prMakeDep

the debugging code printed:

```
going to make an error
I'm having an error
ERROR: Arduino not found
value of q: nil
returning q: nil
   nil
what it returned: nil
```

so it did handle the error and `Quark.parseDependency("Arduino")` returns nil

but collect / do then gets this \init.add

to invoke the bug:

```bash
# fetch the branch https://github.com/supercollider/supercollider/compare/master...crucialfelix:install-quark-dependencies
git checkout 84d1c1bf4983911569bb14ea84225eca22770929
```

```supercollider

["Arduino"].collect({ arg qn; Quark.parseDependency(qn) })


ERROR: Arduino not found
ERROR: Message 'add' not understood.
RECEIVER:
   Symbol 'init'
ARGS:
   nil
CALL STACK:
	DoesNotUnderstandError:reportError   0x11888e588
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x11888f0d8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x11888fa28
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x118890338
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x110f9e808
		arg this = 'init'
		arg selector = 'add'
		arg args = [*1]
	ArrayedCollection:do   0x118d674b8
		arg this = [*1]
		arg function = <instance of Function>
		var i = 0
	Collection:collectAs   0x11363fb28
		arg this = [*1]
		arg function = <instance of Function>
		arg class = <instance of Meta_Array>
		var res = [*0]
	Interpreter:interpretPrintCmdLine   0x118335268
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "["Arduino"].collect({ arg qn..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x111066d08
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'add' not understood.
RECEIVER: init

```

the next commit avoids throwing an error as a means of control flow, instead returning nil from *parseQuarkName

https://github.com/crucialfelix/supercollider/commit/6c994638efbe8f739669724ad441ef90e482f04b
