### ISSUE TITLE
unixCmd adds "sh -c" to the command

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1738]
`sc_popen()` prevents user code from killing a process launched by unixCmd. Among the user impacts, this means the MP3 quark is broken, with no easy workaround.

common/sc_popen.cpp, lines 53-54:

```
    argv[0] = (char *)"sh";
    argv[1] = (char *)"-c";
```

In POSIXy systems, this executes a command that looks like `sh -c user...command...`. Both OSX and Linux respond by creating a process, with one PID, for "sh." Subsequently, "sh" launches another process for the user's command, with a different PID.

In sclang, `unixCmd` returns the PID to the user. However, this is the PID of `sh`. If you then do `"kill -9 %".format(thePid).unixCmd`, the `sh` process will be killed, _but the user-command process keeps running!_

There is no guaranteed, consistent way to extrapolate from the "sh" PID to the user-command PID -- hence, no reliable way to kill the actual command process.
- If there is no concrete benefit to prepending `sh -c`, then... it's actively doing harm, so take it out.
- If there is a good reason to have it, then we need to find some way to make both PIDs available to the user.

**Comment by jamshark70** [comment]
Example with the MP3 quark:

```
SynthDef(\di2, { |bufnum|
	Out.ar(0, DiskIn.ar(2, bufnum));
}).add;

Dialog.openPanel { |path|
	m = MP3(path);
};

m.start;
-> MP3.start completed (PID 21860)

// In terminal:
$ ps x | grep lame
21860 ?        S      0:00 sh -c /usr/bin/lame --decode --silent --resample 44.1  "/home/dlm/Music/ddw_itch_to_scratch.mp3" /tmp/sc3mp3--1907853434.fifo > /dev/null
21862 ?        S      0:00 /usr/bin/lame --decode --silent --resample 44.1 /home/dlm/Music/ddw_itch_to_scratch.mp3 /tmp/sc3mp3--1907853434.fifo
```

Note here that the real `lame` process is 21862, but unixCmd returned the PID 21860.

```
b = Buffer.cueSoundFile(s, m.fifo, 0, 2, 65536);
a = Synth(\di2, [bufnum: b]);

m.stop;

// In terminal:
$ ps x | grep lame
21862 ?        S      0:00 /usr/bin/lame --decode --silent --resample 44.1 /home/dlm/Music/ddw_itch_to_scratch.mp3 /tmp/sc3mp3--1907853434.fifo
```

Oops! `m.stop` did not actually stop.

```
a.free;
m.finish;
b.free;
```

**Comment by danstowell** [comment]
Why does the user-command process keep running? Surely it's a child of the process that you kill, and thus should also be killed.

**Comment by jamshark70** [comment]
I don't know why. I just know that a user on the mailing list reported it on OSX, and I reproduced it in Linux.

Empirically, you cannot rely on the sh process to kill its subprocess(es).

**Comment by crucialfelix** [comment]
use `exec` not `sh`

http://stackoverflow.com/questions/18351198/what-are-the-uses-of-the-exec-command-in-shell-scripts

it will launch the command and will use the same process. the launched command replaces the exec invocation and gets the same pid.

the purpose is to prevent the process from having access to your shell and permissions.

**Comment by crucialfelix** [comment]
actually if its `.unixCmd` then you would expect to be in a shell and most probably your own shell.

so I'm not sure why `sh` is there at all

**Comment by miguel-negrao** [comment]
i think "sh -c" is used because unixCmd receives a string with the entire command instead of an array of strings with each argument. execve expects an array of strings (the arguments), not a single string. In these cases usually sh is used to do the proper splitting of the one string into multiple arguments. Splitting the command string into arguments is probably non-trivial.

A different version of unixCmd could be provided where arguments are separated.

**Comment by jamshark70** [comment]
"Array of strings"... Perhaps, polymorphism tip the rescue? If SequenceableCollection implemented unixCmd to pass the array of strings separately to a new primitive (where the primitive could call execve), it would have two advantages:

1. No new method selector (avoids the confusion of "why so many OS command methods?").

2. String:unixCmd could retain its current implementation. Since it's a subclass, current uses of unixCmd would keep using the old way = backward compatibility.

I don't really see a downside to this.

**Comment by miguel-negrao** [comment]
> "Array of strings"... Perhaps, polymorphism to the rescue?

I attempted a solution to this based on your suggestion. See pull request #1850.

**Comment by miguel-negrao** [comment]
@jamshark70 Does my pull request do address your issue fully ? Do you care to test it, perhaps ?

**Comment by jamshark70** [comment]
I have to upgrade my gcc to 4.8 in order to do that. This is not going to happen tonight. Probably not tomorrow either.

I don't really use the feature myself. But, the MP3 quark doesn't work as advertised. That's why I logged the bug.

**Comment by miguel-negrao** [comment]
In the MP3 quark the stuff with \readurl uses pipes, that wouldn't work with my version of unixCmd. The other part that uses local files should work with the array version of unixCmd. I think doing postOutput = false would achieve the same as > /dev/null.

Also, [it seems](http://stackoverflow.com/questions/392022/best-way-to-kill-all-child-processes) doing kill -pid , so with negative number should kill all process in that process group.

It is still possible for processes to detach themselves by running commands in the shell though, when I need to to detach something on a remote ssh I do `nohup mycmd &`.

**Comment by jamshark70** [comment]
Reopening. As #1856 notes, Array:unixCmd is not implemented in Windows. Work is still pending on this.

**Comment by jamshark70** [comment]
PS Just checked in Windows, and it is an issue here too:

```
s.boot;

s.pid;
-> 4692
```

Task manager showed PID 4692 = "cmd.exe" and PID 3588 = "scsynth.exe." Killing cmd.exe did not kill scsynth.

**Comment by telephon** [comment]
is it fixed by #1856?

**Comment by jamshark70** [comment]
> is it fixed by #1856?

Scroll up just one screenful:

"Reopening. As #1856 notes, Array:unixCmd is not implemented in Windows. Work is still pending on this."

It is not working in all supported operating systems -- therefore the issue is not fully fixed and it would be premature to close the issue.

**Comment by telephon** [comment]
thanks!

**Comment by snappizz** [comment]
Array:unixCmd also doesn't respect the PATH environment variable, and it should. Miguel Negrão suggested that, provided there are no further side effects, we should use the execvp rather than execve.

**Comment by celesteh** [comment]
This bug also effects the OscGroupClient quark on linux and os x.

**Comment by miguel-negrao** [comment]
> This bug also effects the OscGroupClient quark on linux and os x.

The maintainer of that quark can at least fix it in Linux, just use SequenceableCollection#unixCmd instead.

**Comment by miguel-negrao** [comment]
> Array:unixCmd also doesn't respect the PATH environment variable, and it should. Miguel Negrão suggested that, provided there are no further side effects, we should use the execvp rather than execve.

Actually the PATH is used by the shell to search for executables, if you are starting an executable outside of a shell I don't think the PATH variable will or should be used (that's the job of the shell I think.) and with Array:unixCmd you are starting the the executable without using the shell.

**Comment by miguel-negrao** [comment]
> Actually the PATH is used by the shell to search for executables, if you are starting an executable outside of a shell I don't think the PATH variable will or should be used (that's the job of the shell I think.) and with Array:unixCmd you are starting the the executable without using the shell.

Actualy forget that, we can use the execvpe and simulate the shell in using PATH.

**Comment by miguel-negrao** [comment]
> Array:unixCmd also doesn't respect the PATH environment variable, and it should. Miguel Negrão suggested that, provided there are no further side effects, we should use the execvp rather than execve.

Ok, sorry for the spam. Changed execve to execvpe in #3539. 

["echo","hello","world"].unixCmd

-> 25566
hello world

**Comment by celesteh** [comment]
["sleep","10000"].unixCmd does not work on SC 3.8.0 on linux, which makes it an unsuitable workaround in a quark, as there are still supported linux distro versions that only offer this SC version.

**Comment by miguel-negrao** [comment]
> ["sleep","10000"].unixCmd does not work on SC 3.8.0 on linux, which makes it an unsuitable workaround in a quark, as there are still supported linux distro versions that only offer this SC version.

So the quark works in 3.8 but not in 3.9 currently ? If so, you could release a new version which uses  Array:unixCmd. Users in 3.8 should use an older version of the quark.

**Comment by snappizz** [comment]
@celesteh what about `["/bin/sleep", "10000"]`?

**Comment by miguel-negrao** [comment]
> Reopening. As #1856 notes, Array:unixCmd is not implemented in Windows. Work is still pending on this.

On pull #3539 I've implemented Array:unixCmd for windows, but blindly (not test other than it compile in CI). Does anyone want to test this pull on windows ?

    ["git","help"].unixCmd

**Comment by dyfer** [comment]
In case somebody comes aby this discussion in the future:
- the current behavior with adding the shell before a command has been documented in #6842 
- `SequenceableCollection -unixCmd` does not run commands through a shell
- Windows implementation is being fixed/improved currently
