### ISSUE TITLE
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed

### ISSUE THREAD

**Issue by brachna** [supercollider/supercollider#2409]
Windows 8.1 x64
SuperCollider 3.7.2 (both x86 and x64 versions)

Using scide.
Running simple example:
{ SinOsc.ar(800, 0, 0.1) + PinkNoise.ar(0.01) }.play;

gives:
WARNING: server 'localhost' not running.
-> nil

If I try to reboot server I get:
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = 3
ERROR: server failed to start

**Comment by telephon** [comment]
Related: https://github.com/samaaron/sonic-pi/issues/959

**Comment by brachna** [comment]
Update on the issue.
Tried provided version 3.6.6 win32. It works.
The difference is that when launching 3.6.6 for the first time I get Windows Firewall Pop-up and have to accept connection. Then everything works afterwards.
Launching 3.7.2 for the first time doesn't show Windows Firewall Pop-up, nothing to accept.

**Comment by brachna** [comment]
Nevermind, tried re-installing 3.7.2 and manually set accept rules in Windows Firewall for scide, sclang and scsynth - didn't work, same error.

**Comment by bagong** [comment]
On the Sonic-Pi list Mike Guntsche (@maru-sama) had a symptom on Windows 7 where the server wouldn't start with

`Exception in World_New: boost::interprocess_exception::library_error`

He found in an heroic act, that in his case this was a result of boost not being able to create a file because of a missing registry value.

The key is:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData

The standard value for this variable is `C:\AppData`

Mind having a look with regedit?

**Comment by brachna** [comment]
The key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData" exists.
The value is "C:\ProgramData".

**Comment by bagong** [comment]
Okay, thanks. Different issue then... Mike debugged his problem in a development environment. So I guess for now hard to do anything until we know how to reproduce the error... sorry...

**Comment by bagong** [comment]
Would be nice to identify the circumstances under which this occurs.

**Comment by gl33mer** [comment]
I just got something similar:

```
*** Welcome to SuperCollider 3.7.2. *** For help press Ctrl-D.
booting 57110
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = -1073740791
```

**Comment by gl33mer** [comment]
Just got something similar:

```
*** Welcome to SuperCollider 3.7.2. *** For help press Ctrl-D.
booting 57110
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = -1073740791
```

This install was working (though I have gone through an installation and un-install of VS '15')

I'll try uninstlalling and re-installing supercollider.

**Comment by gl33mer** [comment]
Oh. checked with regedit and key is set to` C:/ProgramData`

**Comment by gl33mer** [comment]
Uninstalled/Reinstalled supercollider.
Still same error. 
Moved all installed quarks and extensions to no avail.

**Comment by bagong** [comment]
Thanks for your efforts! I am sorry you have these problems. I've heard this a few times now, but nobody was able to reproduce the problem yet, so there is not much we can do. Just in case you have a bit of patience left: could you try 3.8 beta?

https://github.com/supercollider/supercollider/releases/tag/Version-3.8.0-beta1

**Comment by brachna** [comment]
Tried all three:
SuperCollider-Win-3.8.0-beta1_32bit-MW-supernova-0962eaf.exe
SuperCollider-Win-3.8.0-beta1_32bit-VS-SonicPi-0962eaf.exe
SuperCollider-Win-3.8.0-beta1_64bit-0962eaf.exe

Unfortunately all have the same error.

**Comment by gl33mer** [comment]
No worries. 

I just tried the 64bit beta and the same error.

Tried undoing any changes made (conf files, etc.) nothing is working.

This installation was working.

(maybe a windows 10 update. I'm running a 64 bit system btw)

**Comment by bagong** [comment]
I have 3.8 running on 3 Win10 pro 64-bit systems with the latest updates, so I don't think it's the Windows version/revision. Sorry...

**Comment by bagong** [comment]
Below seems to be the boost code that leads to the error. Can anybody draw conclusions from this?

http://www.boost.org/doc/libs/1_46_0/boost/interprocess/detail/intermodule_singleton.hpp

Or maybe something useful is hidden here? :

https://github.com/networkMe/missinghud2/issues/8

On my working system a folder inside `C:\ProgramData\boost_interprocess` named `1477691877` containing a file `SuperColliderServer_57110` is created when the server is booted. Just the file is deleted after server.quit, the folders remain. Yet I can delete even the `boost_interprocess` folder and it will be recreated on the next server boot. So you may want to try deleting those, if they are in place. There are/should be no user-right definitions on folders and file.

**Comment by gl33mer** [comment]
I have tried deleting the boost_interprocess folder and the inner folder and the file that's in it already, it did not help.

**Comment by bagong** [comment]
Sorry, I have no ideas left...

**Comment by gl33mer** [comment]
I have not used ccleaner lately and its process doesn't seem to be running. Firewall/antivirus/optimization soft. hasn't changed since the installation was still working.

**Comment by vivid-synth** [comment]
@brachna @gl33mer does ```scsynth``` successfully boot if you call it from the command line (without ```sclang```)?

Try ```scsynth -u 57110```

**Comment by brachna** [comment]
@vivid-synth 
No, I get:
Exception in World_New: boost::interprocess::intermodule_singleton initializatio
n failed
And scsynth crashes.

**Comment by gl33mer** [comment]
@vivid-synth  I get the same behavior as @brachna

**Comment by awson** [comment]
Same here (Windows 10AU 64-bit, SuperCollider-Win-3.8.0-beta1_64bit-0962eaf.exe).

There is a lot of mentions of this in internet. The **ONLY** truly working solution for me is [the patch by Valentin Shtronda](https://svn.boost.org/trac/boost/ticket/12137).

**Comment by bagong** [comment]
Yess, that seems to be it! Thanks a lot!!!
If I delete the system log and start the server I get the error!
After a reboot, eventID 6005 is recreated and it works again as expected.
Could the others try this "fix"?

**Comment by bagong** [comment]
The patch would apply in 1.61 too, it seems, the file seems unchanged...

**Comment by bagong** [comment]
The milestone is tentative...

**Comment by llloret** [comment]
The patch looks quite safe. I would say it is worth doing it and giving it a try. I will try to make a PR tomorrow

**Comment by vivid-synth** [comment]
Maybe we can submit the patch to boost also?

**Comment by llloret** [comment]
Hi, I have just made a PR for 3.8 branch. If someone can give it a try, that would be great.

**Comment by bagong** [comment]
I've uploaded 64- and 32-bit Visual Studio builds into the 3.8-beta1 release page that contain the above-mentioned patch. The filenames have appended TEST-server-boot.

You need to delete Windows system log. The quickest way to do that (Win10), I think, is right click the "start button" at the bottom left, choose "Event Viewer", open "Windows Logs", right click "System", and choose "Clear Log...". I hope all Windows flavors have that Management Console. Mine is Windows 10 Pro.

Note that I in one case I had to boot the server three times to trigger the error, but once it occurred it happened repeatedly. Then again it returned to work as hoped. So you might need a bit of patience when trying.

**Comment by brachna** [comment]
New test builds with patch are working!

**Comment by bagong** [comment]
@brancha: Great, thank you for testing! Could you do me a favor, and boot the server 10 or so times, just to see if it's really reliable. I've seen machines where that was not the case.

**Comment by brachna** [comment]
I assume you means message like this:

Device options:
  - MME : Переназначение звуковых устр. - Input   (device #0 with 2 ins 0 outs)
  - MME : Микрофон (Realtek High Definiti   (device #1 with 2 ins 0 outs)
  - MME : Переназначение звуковых устр. - Output   (device #2 with 0 ins 2 outs)
  - MME : Динамики (Realtek High Definiti   (device #3 with 0 ins 8 outs)
  - Windows DirectSound : Первичный драйвер записи звука   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Микрофон (Realtek High Definition Audio)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Первичный звуковой драйвер   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Динамики (Realtek High Definition Audio)   (device #7 with 0 ins 8 outs)
  - Windows WASAPI : Динамики (Realtek High Definition Audio)   (device #8 with 0 ins 2 outs)
  - Windows WASAPI : Микрофон (Realtek High Definition Audio)   (device #9 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #10 with 0 ins 8 outs)
  - Windows WDM-KS : Стерео микшер (Realtek HD Audio Stereo input)   (device #11 with 2 ins 0 outs)
  - Windows WDM-KS : Лин. вход (Realtek HD Audio Line input)   (device #12 with 2 ins 0 outs)
  - Windows WDM-KS : Микрофон (Realtek HD Audio Mic input)   (device #13 with 2 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #14 with 0 ins 2 outs)

Booting with:
  In: MME : Микрофон (Realtek High Definiti
  Out: MME : Динамики (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Receiving notification messages from server localhost
Cannot connect to shared memory: �� ������� ����� ��������� ����.
ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER:
Instance of ServerShmInterface {    (000000425270E5B8, gc=78, fmt=00, flg=00, set=02)
  instance variables [2]
    ptr : nil
    finalizer : nil
}

PROTECTED CALL STACK:
	Meta_MethodError:new	00000042500B8C40
		arg this = PrimitiveFailedError
		arg what = Failed.
		arg receiver = a ServerShmInterface
	Meta_PrimitiveFailedError:new	00000042500BF200
		arg this = PrimitiveFailedError
		arg receiver = a ServerShmInterface
	Object:primitiveFailed	000000420F4ED380
		arg this = a ServerShmInterface
	a FunctionDef	0000004250C65DC0
		sourceCode = "<an open Function>"
	Routine:prStart	00000042507168C0
		arg this = a Routine
		arg inval = 36.102939

CALL STACK:
	MethodError:reportError   0000004251413DF8
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >   000000420F543B48
		arg error = <instance of PrimitiveFailedError>
	Integer:forBy   0000004251823238
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo   00000042511249D8
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_   0000004251414FD8
		arg this = <instance of Scheduler>
		arg newSeconds = 36.9134447
	Meta_AppClock:tick   000000420F540918
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick   00000042510D2EF8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER: a ServerShmInterface

**Comment by bagong** [comment]
Yes, exactly. Sorry you see that too...

**Comment by brachna** [comment]
Sometimes I have to reboot, but that's still miles better than not working at all. No problem.

**Comment by bagong** [comment]
If we could get it to a really reliable state, I'd strongly prefer ;). Btw, if it's just about getting the system to work, I think you should get a stable situation by deleting the system log and rebooting. Then even the later error you posted should be gone.
One thing is to bring your system in a state that it runs SC well, the other is to make SC robust enough to work around problems on less optimal systems. It does look like we're dealing with the second case here, which is a valid one, of course.
But I really value your happiness ;)

**Comment by crucialfelix** [comment]
So this is fixed (and merged for 3.8), but perhaps not 100% solved ?

**Comment by crucialfelix** [comment]
Re-open or let's open a new one if there is a related but different issue still to be solved. thx

**Comment by vivid-synth** [comment]
Reopening as this seems to still be an issue.

It seems that the Boost patch in https://github.com/supercollider/supercollider/pull/2457 is causing crashes on some machines (is this right @llloret ?). If so, can I suggest we try and do the fix upstream, on the proper boost repo? ( https://github.com/boostorg/interprocess )

**Comment by bagong** [comment]
No @vivid-synth , this is not right. The patch is not causing the crashes, it is preventing most of them, but not yet all. The Windows-related server boot error reports on Sonic Pi have gone down significantly since the patch was applied. The remaining problems cannot be reproduced yet.

**Comment by vivid-synth** [comment]
Ah @bagong I stand corrected. Still, since we're making real changes here, should we still not try and submit them upstream (and get review from the Boost people)?

**Comment by bagong** [comment]
Sure, if somebody has the guts to take it up with boost ;) I just opposed your wording because that could be read as suggesting to revert the patch - which in turn would make the situation worse than it is now.

**Comment by llloret** [comment]
As far as I understand it is already reported in Boost.

**Comment by bagong** [comment]
Looks better with the update to boost 1.63! Without patch the boot behaviour is better than with the patch and boost 1.61. I got 2 boot failures (of the second) for about 30 times booting. Also the old behaviour that failure probability would raise over time seems to be gone.

**Comment by brianlheim** [comment]
@bagong Brilliant! Thanks for checking!

**Comment by llloret** [comment]
Great. @bagong, so is the patch included on that boost version?

But, we will still need to understand what's causing the issue in the 2
instances where our failed...

>

**Comment by bagong** [comment]
I didn't look, but I verified that deleting the system log doesn't prevent booting the server anymore ;) That was the reproducible part of it.

Yea, for issue two we need a reproducer. Fortunately it's very rare. People that are hit by it usually just seem to try to reboot the server, find that it works then, and go on happily ;)

**Comment by hyphz** [comment]
Still happening in 3.9.3 on Windows 10 here.

**Comment by linkpy** [comment]
Hey there.
I'm still having this issue using 3.9.3 on Windows 10 too :(

**Comment by hyphz** [comment]
Apparently it's because Boost tries to read the system log as it starts up to find the last boot time to use as a nonce. "Do it a less ridiculous way" seems like a solution ;)

**Comment by linkpy** [comment]
Yes I read this. But they applied a patch to use `GetTickCount64` for the 3.8, or am I being dumb and didn't understood everything ? x)

**Comment by fmedio** [comment]
Hi team, I am still seeing this issue in windows 10 (64 bit) with SuperCollider 3.10.0.
Any ideas?
Thanks in advance!

**Comment by fmedio** [comment]
SuperCollider uses Boost for inter-process communication (IPC). Boost IPC creates a set of files under a temp directory upon startup. Boost appends the node's uptime to that directory's name in an effort to make it unique. The Windows implementation of the uptime lookup is brittle, it seems to search for events of type '6005' (logon) in the Windows event log. This apparently fails many different ways, possibly when the event log becomes too large. Here is a workaround that worked on Windows 10:

- stop SuperCollider, confirm sclang/scide/scsynth are down with TaskManager
- Open Event Viewer, delete all application and system logs
- Open powershell as administrator, add a 6005 event like so:  write-eventlog -logname System -source 'EventLog' -EventID 6005 -EntryType Information -Category
 0 -message "foobar"
- Restart SuperCollider

**Comment by changshen** [comment]
This problem is still there for verion 1.72 with Window 10 when I did telework and reboot machine.  fmedio's method solve the problem:
"write-eventlog -logname System -source 'EventLog' -EventID 6005 -EntryType Information -Category 0 -message "foobar""

**Comment by saturnation** [comment]
I just had this error and found this issue. I saw @fmedio's solution. Before implementing it I searched the events and found that there were no '6005' events in the system logs. Before inserting one, I restarted the computer and checked the event viewer. This time there was a '6005' event. When I tried booting the server there was no error. For me the key was the lack of a logon event.

**Comment by dyfer** [comment]
For devs: here's a stackoverflow post with suggestions for possible workarounds: https://stackoverflow.com/questions/39742630/boost-shared-memory-cant-be-initialized

**Comment by dyfer** [comment]
If anyone comes across this issue, it is now fixed in the develop builds and will be included in the upcoming 3.12 release.
