### ISSUE TITLE
setting clientID to > 0 fails -> proposal for cleanup

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#2940]
Setting s.clientID to > 0 fails in current 3.9dev. 
I started a topic branch that fixes that, and cleans up related details along the way:
https://github.com/supercollider/supercollider/tree/topic-server-fix-multi-clientIDs
There is a longer discussion and tests in Guides/MultiClient_Setups.schelp.

Short story and tests: 
scsynth can be used by multiple clients simultaneously, and the Server object supports that by using its clientID to allocate different ranges for nodeIDs, buffers and busses.
```
// test default case - clientID 0 - works in 3.8.0, and current 3.9.0:
s.options.maxLogins_(4);  // default is 0, 4 divides number ranges for 4 clientIDs
s.clientID_(0);   // 1
s.defaultGroup;   // 1
10.collect { s.nextNodeID };  
10.collect { Buffer(s).bufnum };
10.collect { Bus.audio(s).index };
10.collect { Bus.control(s).index };

// this works in 3.8.0,  and fails in 3.9d [372d364] (june 2017)
s.clientID_(1);

// so these report behavior only from 3.8.0:
s.defaultGroup;    // same defaultGroup as clientID 0 - better if different for each clientID
10.collect { s.nextNodeID };        // OK
10.collect { Buffer(s).bufnum };    // OK
10.collect { Bus.audio(s).index };  // OK
10.collect { Bus.control(s).index };// OK
```

**Comment by muellmusik** [comment]
Hi Alberto! 

What I don't understand is, why do you need to manually set client IDs? The scsynth instance should do this automatically without problem providing ```maxLogins``` has been set correctly. This has been the case since 2f6b10ef96d3ba54cb2bcee79c79e06825219ca0.

The clientID arg to Server:new and Server:remote was kept for backwards compatibility, so of course that should work if we're keeping it, but AFAIK, ```clientID_``` was not intended to be a public setter.

I think getting the scsynth instance to allocate IDs is far superior, mostly because it is the one centralised place to do so. I don't know what changed in 3.9 (@telephon?), but I think it would make sense to work towards fixing that if there's an issue with it now, unless there's something you need that's impossible to deliver that way.

It might also be best to deprecate/remove the old clientID interface, since it adds complexity and probably doesn't see much use.

**Comment by adcxyz** [comment]
Ah sorry, did not explain fully: 
I am using that interface here just to show the error. The same error also happens when you try to create a server with a fixed clientID, as in:
```
Server(\adc, NetAddr.localAddr, s.options, 1);
```
and it happens when you log into a server from a second laptop/client, get back clientID 1, and boom, the allocators break. You just never see this with a single computer, because the first client always gets clientID 0 ;-)

Yes, fully agreed that the automatic response clientID interface is the best default solution. 
Manually setting clientID can still be useful, as e.g. when you know the exact list of clients beforehand,  and using fixed clientIDs for them makes other things easier and more stable/tractable.  So I would really prefer to keep that option available rather than deprecating/removing it.

**Comment by muellmusik** [comment]
Okay so the problem only happens with manually supplied IDs?

> Manually setting clientID can still be useful, as e.g. when you know the exact list of clients beforehand, and using fixed clientIDs for them makes other things easier and more stable/tractable. So I would really prefer to keep that option available rather than deprecating/removing it.

Okay, if it makes any difference, IIRC scsynth always returns the same ID to an address it's already seen so nothing shifts if someone rejoins.

Of course the best solution would be to move the allocation process into scsynth as well. I think this could work easily with clients using UUIDs to request a resource. But that would be a bigger change!

**Comment by adcxyz** [comment]
btw, please see the longer explanations in Guides/MultiClient_Setups.schelp

**Comment by muellmusik** [comment]
> hm, IIUC that would double traffic, no?
> you request an ID for a synth, the synth starts, and scsynth sends back the ID it gave it.
> If it works cleanly on the sclang side, I am fine with keeping it there.

No, you generate a UUID. Existing node IDs are just labels anyway (that happen to be implemented as ints) so what matters is that the ID is unique. scsynth does the bookkeeping to match a node to its label. If you know the label is unique there's no need for a reply.

This could also work for Busses and Buffers.

> Unless there is a really strong reason for major surgery, better avoid the work ;-)

Yes, I'd thought of this more as an SC4 kind of thing, though I'm convinced it would massively simplify multi-client situations.

> Btw, please see the longer explanations in Guides/MultiClient_Setups.schelp for the finer points :-)

Yes, I've added some comments to the relevant commits.

**Comment by muellmusik** [comment]
> No, you generate a UUID. Existing node IDs are just labels anyway (that happen to be implemented as ints) so what matters is that the ID is unique. scsynth does the bookkeeping to match a node to its label. If you know the label is unique there's no need for a reply.

Maybe clearer: nodes are stored in a hash table in scsynth. Currently we generate a node ID using the allocator. This ID is *not* guaranteed to be unique, which creates a lot of complexity client-side. Using a UUID would make it guaranteed unique.

For Buffers and Busses, you could use a similar process, perhaps with a bit of mapping. Adjacency would need to be dealt with, but again that would still simplify matters overall I think.

Apportioning parts of a shared network resource is best centralised I think. The one central place is in scsynth itself.

**Comment by muellmusik** [comment]
Okay, so a little more:

If we do need to have the ability to change a clientID after the server is set, then I think we should just separate the public and private parts, e.g.

```
	clientID_ { |val|
		userSpecifiedClientID = true;
		this.prSetClientID(val);
	}

	prSetClientID { |val|
		if(val.isInteger.not) {
			"Server % couldn't set client id to: %".format(name, val.asCompileString).warn;
			^this
		};
		if(clientID != val) {
			clientID = val;
			this.newAllocators;
		}
	}
```

But if we do that then it should probably be named something else, e.g. resetClientIDandAllocators to make it clear that you're not just changing the clientID, you're resetting the allocators and possibly leading to conflicts with any existing nodes etc. you have.

I think we also need to make it clear that you cannot mix automatic and manual clientIDs. (Sorry that is a real weakness in my original version, but TBH I only imagined manually set clientIDs as a backwards compatibility thing, so didn't foresee there could be conflicts)

**Comment by muellmusik** [comment]
That said, I still think the best approach is a very robust centralised and automated scheme. If anyone has had issues with that as is, please let me know. The only potential problem I could think of was something like this:

- client connects to a server
- loses wifi (without properly disconnecting from the server)
- reconnects with a different (new) address
- can't reconnect to server because of maxlogins exceeded

Note that this is a problem with or without this branch. One workaround is simply to have more logins, but that's a bit crappy. Another is to hard assign IP addresses in your router. Currently scsynth stores clients via ReplyAddress, which is why the issue arises. I don't think this is an unreasonable approach, but we could allow something else, like a user defined name for instance.

**Comment by muellmusik** [comment]
Another improvement that could take advantage of the centralised approach would be that notify responds with the num of maxLogins as well as a clientID. This would remove the need for coordination on clients and make it automatically correct.

**Comment by adcxyz** [comment]
@muellmusik - thanks for all the ideas, and the tough criteria, all for that!
answers per topic:  
* yes, getting maxLogins from the scsynth would be best! doable for 3.9?
* happy with clientID_ and prSetClientID, will change branch for that.
* access to userSpecifiedID itself is not really needed, I can live without it ;-), will remove it.
* will write up some setup scenarios for fixed numbers, for illustration, 
and as guide/tutorial material. 

* UUID was only intended for the todo later list, right?
* encapsulation vs. snoopability is generally really interesing and should be part of the SC coding style guide discussion
* another cleanup note  - ATM failOSCfunc throws an error and recommends reboot, when one does server.notify twice - It could check whether the failure message is 'already notifying', and just inform the user with a post, not a long error trail. 
thanks!

**Comment by muellmusik** [comment]
> thanks for all the ideas, and the tough criteria, all for that!

Sorry I'm such a pain! (Really!) But I know what hostages to fortune we can create if we get this basic stuff wrong, so I think it's worth questioning these things.

> yes, getting maxLogins from the scsynth would be best! doable for 3.9?

Yes, I can do the server-side if you like. It wouldn't take long.

> happy with clientID_ and prSetClientID, will change branch for that.

Okay. Are you absolutely sure it's necessary? I'm still not clear to be honest on why one would need to create a Server and then change its client ID. You've said it's for stability but I'm worried it may result in the opposite. Again I'm very happy to work with you guys to try to make the automatic thing work robustly if that's lacking in some way, but I've still not heard of any specific problems.

> UUID was only intended for the todo later list, right?

It would be a major change in the API, and the lang side Server management. It could possibly be done with backward compatibility, but the options for that (new OSC messages, or check for arg type) are messy. It would be cleaner to do it as a big break.

> encapsulation vs. snoopability is generally really interesing and should be part of the SC coding style guide discussion

Well, it's a general OOP principle, or?

> another cleanup note - ATM failOSCfunc throws an error and recommends reboot, when one does server.notify twice - It could check whether the failure message is 'already notifying', and just inform the user with a post, not a long error trail.
> thanks!

Ah I see. Yes, I think that got added when ServerStatusWatcher came in. The original looked like this:

```
			failOSCFunc = OSCFunc({|msg|
				if(msg[3].notNil && { msg[3] != clientID }, {
 					clientID = msg[3];
 					this.newAllocators;
 				});
 				doneOSCFunc.free;
 			}, '/fail', addr, argTemplate:['/notify', nil, nil]).oneShot;
```
So if it returned the existing clientID it did nothing, silently. That seems correct to me. I'm not sure about what it did if it got a different one, which is silently reset the ID and added new allocators. @telephon do you have a view on this?

**Comment by adcxyz** [comment]
>> yes, getting maxLogins from the scsynth would be best! doable for 3.9?
> Yes, I can do the server-side if you like. It wouldn't take long.
yes please!

>>  happy with clientID_ and prSetClientID, will change branch for that.
> Okay. Are you absolutely sure it's necessary? 
Well, removing it would be an API change ;-P - I am happy to review removing it later,  
but I think for testing until we are sure things are really rock-solid it will be useful to keep it. 

> failOSCFunc
IMHO the logic should be 
- figure out what best to do, do what is best, 
- post clear short info on what got done.
- and post errors when things did really go wrong :-)

so default case - scsynth sets ID - do it and post "Server x - setting clientID to 0 ."
if userSpecified, and scsynth tries to set id: do nothing and post somehting like 
"scsynth tried to set id, but clientID is userspecified, so clientID still is 0."
if already notified, post "server x is already notified, clientID is 0."
etc

**Comment by muellmusik** [comment]
> Well, removing it would be an API change ;-P -

Well, sort of, but only just, as it went out in 3.8: I checked back and it wasn't me actually. The setter was added only when ServerStatusWatcher was changed to handle notification. It wasn't documented and I don't think was meant to be public. If ServerStatusWatcher or some other external object is still going to handle it, then we need to distinguish between that and explicit user setting.

> so default case - scsynth sets ID - do it and post "Server x - setting clientID to 0 ."
> if userSpecified, and scsynth tries to set id: do nothing and post somehting like
> "scsynth tried to set id, but clientID is userspecified, so clientID still is 0."
> if already notified, post "server x is already notified, clientID is 0."
> etc

Well, I think more robust would be: you supply an ID at creation time, and then register to notify, explicitly asking for that ID. If that ID is already taken by another ReplyAddress, it fails. (post as you wish) This would alert you to manual screw-ups, and to cases where people have accidentally mixed manual and automatic approaches.

I could do that, but again cleaner and easier to maintain would be to just require the automatic approach, assuming that works without issue. The clientID arg could be 'deprecated' by keeping it for a while but posting a warning that it's being ignored.

**Comment by adcxyz** [comment]
>> Well, removing it would be an API change ;-P -

> Well, sort of, but only just, as it went out in 3.8: I checked back and it wasn't me actually. The setter was added only when ServerStatusWatcher was changed to handle notification. It wasn't documented and I don't think was meant to be public. 

OK, sorry, was only meant as a joke, and was not that funny - apologies. I had not traced back and did not know that the (otherwise really nice) refactor of the watchery stuff exposed clientID_. 

How about this: 
We keep the private method prSetClientID as it is now, (because StatusWatcher needs it)
remove the public method clientID_,  and leave userSpecifiedClientID as settable only on creation. 
Would that work for you? 
I hope all else in this branch is close to being OK, so it could be ready soon.

> Well, I think more robust would be: you supply an ID at creation time, and then register to notify, explicitly asking for that ID. If that ID is already taken by another ReplyAddress, it fails. (post as you wish) This would alert you to manual screw-ups, and to cases where people have accidentally mixed manual and automatic approaches.

Yes, makes good sense. I don't really understand all the possible cases this, so I'd be happy to hash out all the possible cases with you, and write up what the best next actions and user info are for each case. That can also go into in a separate topic branch, rather than this one, yes?

Again, thanks for your precision and patience,
best adc

**Comment by muellmusik** [comment]
> OK, sorry, was only meant as a joke, and was not that funny - apologies. I had not traced back and did not know that the (otherwise really nice) refactor of the watchery stuff exposed clientID_.

Sorry didn't mean to seem humourless, just wanted to be clear about its provenance. Removing a used bit of the API is of course a real issue.

> We keep the private method prSetClientID as it is now, (because StatusWatcher needs it)
> remove the public method clientID_, and leave userSpecifiedClientID as settable only on creation.
> Would that work for you?

That's fine with me. With the proposed scsynth changes that's at least more robust than the current situation. We can then test the hell out of it and revisit deprecating the manual IDs if that makes sense.

> That can also go into in a separate topic branch, rather than this one, yes?

You mean the write up, or the server changes?

One query: If the requested ID is already taken, should it return a free one? That would allow you to move on immediately with no fixes.

> Again, thanks for your precision and patience,

Sorry, I feel like I'm being really difficult! I guess I was partly just surprised as I thought this was all working well for years. Thanks for *your* patience!

**Comment by adcxyz** [comment]
>> That can also go into in a separate topic branch, rather than this one, yes?

> You mean the write up, or the server changes?

Both - we can just open an issue for it, discuss there until we have a full list we like, 
and then implement according to that list.

> One query: If the requested ID is already taken, should it return a free one? That would allow you to move on immediately with no fixes.

yes, I think handing out the next free one is good!

**Comment by muellmusik** [comment]
Okay, I've added a branch for a better server notify here: https://github.com/supercollider/supercollider/tree/topic/improved-server-notify

Have a look. I haven't had a chance to properly test the requesting of client IDs since it's broken in master anyway. I think you'll need to merge into this branch to test properly. But...

- it now returns maxLogins. 
  - lang sets this in a server's options if it's wrong.
  - It currently doesn't warn if this has happened, but maybe it should
- You can now request a clientID and scsynth will reply with an alternate if it's claimed
  - again no warning yet, but...
  - I'm not sure if this should be a done or a fail or something else. Currently its /done
- I also fixed a very old deregistering to notify bug (I guess nobody ever does that)
- I also added SendDoneWithVarArgs and SendFailureWithVarArgs funcs. These should possibly be generalised into a SendReplyWithVarArgs

**Comment by adcxyz** [comment]
@jamshark70 -
Since you wrote ContiguousBlockAllocator, I'd like to ask your opinion esp. of 
ContiguousBlockAllocatorWithOffset: di you see any problems with it? 
and would you agree to merge its use of addrOffset back into ContiguousBlockAllocator?

@muellmusik - I hope all issues raised are addressed, so this is ready to become a PR, yes?
(If so, I would prepare for PR by removing the differences discussion sections, and add help files for the final ContiguousBlockAllocator and ReadableNodeIDAllocator classes.)

**Comment by muellmusik** [comment]
@adcxyz Do you not want to test merging in the other branch with this? I think that's a more comprehensive solution to the general issue.

**Comment by adcxyz** [comment]
As this one is ready, I thought it better to make sure it still gets into 3.9,
and do the improved responses in a second PR (which hopefully would also make it :-)
Ok, will try to test ASAP, adc

**Comment by adcxyz** [comment]
hi,
I merged improved-server-notify, 
and put in more detailed responses in the notify OSCfuncs, 
and here are the tests:

// default settings:
s.numUsers; // 1
s.clientID; // 0
s.boot;     // posts:
// -> Requested notification messages from server 'localhost'
localhost: scsynth has maxLogins 1 - adjusting my options accordingly.
localhost: keeping clientID 0 confirmed from scsynth.

// try logging in too often:
s.notify_(true);
s.notify_(true);
// -> says already notified

// try logging out too often:
s.notify_(false);
s.notify_(false);
// -> says not registered

// try setting illegal maxLogins:
s.options.maxLogins_(4);
s.notify_(false);
s.notify_(true);  // log in again -> maxLogins gets adjusted to scsynth
// -> Requested notification messages from server 'localhost'
localhost: scsynth has maxLogins 1 - adjusting my options accordingly.
localhost: keeping clientID 0 as confirmed from scsynth.

// try log in with a userSpecified fixed clientID 
s.notify_(false);
s.options.maxLogins_(4);
// copy of s, but with new clientID;
x = Server(\test, s.addr, s.options, clientID: 3);

// id ranges are offset now!
x.nextNodeID;
Buffer(x);
Bus.audio(x);


// request a free clientID from another laptop:
z = Server.remote(\chak, s.addr, s.options);

@muellmusik - is the client matching for ip and port? 
I think it should be, then it would work to have two clients 
from different SC-based apps on the same computer, distingushed by port number.

that is how far I got - looks good so far, no? 
best adc

**Comment by telephon** [comment]
btw. I think this whole `clientID` setter thing is probably my fault – in the huge server refactoring it might have sneaked through. So I would *not* call any change in this or similar respect an API change (yet).

**Comment by adcxyz** [comment]
I think it was your factoring out the watching, and I was not aware of the history of it, 
such recent changes would not count as API change, agreed. 
BTW, it occurred to me today that for all running servers, (both local and remote), on login one should always ask for their FULL config and set (a copy of) the server object's options accordingly - then one really always has the exact state of the real thing - default valus where options were not set before booting,  requested hardware not available, samplerate adjusted by hardware etc.

**Comment by muellmusik** [comment]
> @muellmusik - is the client matching for ip and port?

Yes, it should, as ReplyAddress has == and <

> looks good so far, no?

Yes.

> I think it was your factoring out the watching, and I was not aware of the history of it,
> such recent changes would not count as API change, agreed.

We should probably remove the clientID setter before this is released again though, if we're in agreement about that. (But I think that's done now?)



> BTW, it occurred to me today that for all running servers, (both local and remote), on login one should always ask for their FULL config and set (a copy of) the server object's options accordingly - then one really always has the exact state of the real thing - default valus where options were not set before booting, requested hardware not available, samplerate adjusted by hardware etc.

Yes, also if one uses the same set of base options for more than one server it's a bit bad if these things are modified. So yes, it should make a copy, and that should also be documented.

**Comment by telephon** [comment]
there are some older notes here, too: https://github.com/supercollider/supercollider/wiki/notes-for-refactoring-the-server-implementation

**Comment by jamshark70** [comment]
> Since you wrote ContiguousBlockAllocator, I'd like to ask your opinion esp. of ContiguousBlockAllocatorWithOffset: di you see any problems with it? and would you agree to merge its use of addrOffset back into ContiguousBlockAllocator?

I think the concept is fine. I don't have time for a complete review, but be very very careful about subtracting `addrOffset` -- for example, this is suspicious:

- `reserve()` does `address = address - addrOffset;` (line 21)

- ... and later `new = this.prReserve(address, size, block);` (line 30, 39) -- that is, the address being passed to `prReserve` is already adjusted to start with 0, but...

- `prReserve` *also* does `address = address - addrOffset;` (131) -- it expects the real address, not the adjusted-to-0 address.

It might be better to use `address` throughout the class to mean only and always the real address. The only reason for the offset is to index into `array` -- so you could go through and rigorously subtract the offset for every `array` access, but only in those places. The array is internal, so it's not an API change. (`freed` is a dictionary whose keys are block sizes, so no need to change anything for it.)

If the class's logic is sound and it passes tests, then I'd say, yes, merge it. In `ContiguousBlockAllocator`, a nonzero `pos` at initialization time results in wasted array slots. That's a definite weakness, which the offset would overcome.

**Comment by jamshark70** [comment]
PS I apologize for my dreadful coding style at the time I wrote it. Feel free to change things like:

```
		(block = this.findAvailable(n)).notNil.if({
			^this.prReserve(block.start, n, block).start
			+ addrOffset;
		}, { ^nil });
```

to

```
		block = this.findAvailable(n);
		if(block.notNil) {
			^this.prReserve(block.start, n, block).start
			+ addrOffset;
		} {
			^nil
		};
```

(and that's not even the worst one)

**Comment by jamshark70** [comment]
This diff appears to function correctly.

**Test code:**

```
a = ContiguousBlockAllocator(20, 0, 100);

a.debug;

b = a.alloc(2);  // 100, correct

a.debug;

c = a.alloc(2);  // 102, correct
d = a.alloc(3);  // 104, correct

a.free(c);

a.debug;

c = a.alloc(1);  // 102, correct

a.debug;
->
Array:
0: ContiguousBlock(100, 2, true)
2: ContiguousBlock(102, 1, true)
3: ContiguousBlock(103, 1, false)
4: ContiguousBlock(104, 3, true)
7: ContiguousBlock(107, 13, false)

Free sets:
1: IdentitySet[ ContiguousBlock(103, 1, false) ]
```

At the end, it is in the correct state: 2 reserved, 1 reserved, 1 free, 3 reserved, the rest free.

**Diff:**

```
dlm@hjh-e431:~/share/sc-hjh.git$ git diff SCClassLibrary/Common/Control/
diff --git a/SCClassLibrary/Common/Control/Engine.sc b/SCClassLibrary/Common/Co
index 9cc31af..0967460 100644
--- a/SCClassLibrary/Common/Control/Engine.sc
+++ b/SCClassLibrary/Common/Control/Engine.sc
@@ -195,11 +195,11 @@ ContiguousBlock {
 
 
 ContiguousBlockAllocator {
-       var     size, array, freed, pos, top;
+       var     size, array, freed, pos, top, offset;
 
-       *new { |size, pos = 0|
-               ^super.newCopyArgs(size, Array.newClear(size).put(pos, Contiguo
-                       IdentityDictionary.new, pos, pos);
+       *new { |size, pos = 0, offset = 0|
+               ^super.newCopyArgs(size, Array.newClear(size).put(pos, Contiguo
+                       IdentityDictionary.new, pos + offset, pos + offset, off
        }
 
        alloc { |n = 1|
@@ -211,7 +211,7 @@ ContiguousBlockAllocator {
 
        reserve { |address, size = 1, warn = true|
                var     block, new;
-               ((block = array[address] ?? { this.findNext(address) }).notNil 
+               ((block = array[address - offset] ?? { this.findNext(address) }
                                { block.used and:
                                { address + size > block.start } }).if({
                        warn.if({ "The block at (%, %) is already in use and ca
@@ -240,15 +240,15 @@ ContiguousBlockAllocator {
                        prev, next, temp;
                // this 'if' prevents an error if a Buffer object is freed twic
                if(address.isNil) { ^this };
-               ((block = array[address]).notNil and: { block.used }).if({
+               ((block = array[address - offset]).notNil and: { block.used }).
                        block.used = false;
                        this.addToFreed(block);
                        ((prev = this.findPrevious(address)).notNil and: { prev
                                (temp = prev.join(block)).notNil.if({
                                                // if block is the last one, re
                                        (block.start == top).if({ top = temp.st
-                                       array[temp.start] = temp;
-                                       array[block.start] = nil;
+                                       array[temp.start - offset] = temp;
+                                       array[block.start - offset] = nil;
                                        this.removeFromFreed(prev).removeFromFr
                                        (top > temp.start).if({ this.addToFreed
                                        block = temp;
@@ -258,8 +258,8 @@ ContiguousBlockAllocator {
                                (temp = next.join(block)).notNil.if({
                                                // if next is the last one, red
                                        (next.start == top).if({ top = temp.sta
-                                       array[temp.start] = temp;
-                                       array[next.start] = nil;
+                                       array[temp.start - offset] = temp;
+                                       array[next.start - offset] = nil;
                                        this.removeFromFreed(next).removeFromFr
                                        (top > temp.start).if({ this.addToFreed
                                });
@@ -280,8 +280,8 @@ ContiguousBlockAllocator {
                        });
                });
 
-               (top + n > size or: { array[top].used }).if({ ^nil });
-               ^array[top]
+               (top + n - offset > size or: { array[top - offset].used }).if({
+               ^array[top - offset]
        }
 
        addToFreed { |block|
@@ -297,18 +297,18 @@ ContiguousBlockAllocator {
 
        findPrevious { |address|
                forBy(address-1, pos, -1, { |i|
-                       array[i].notNil.if({ ^array[i] });
+                       array[i - offset].notNil.if({ ^array[i - offset] });
                });
                ^nil
        }
 
        findNext { |address|
                var     temp;
-               (temp = array[address]).notNil.if({
-                       ^array[temp.start + temp.size]
+               (temp = array[address - offset]).notNil.if({
+                       ^array[temp.start + temp.size - offset]
                }, {
                        for(address+1, top, { |i|
-                               array[i].notNil.if({ ^array[i] });
+                               array[i - offset].notNil.if({ ^array[i - offset
                        });
                });
                ^nil
@@ -333,9 +333,9 @@ ContiguousBlockAllocator {
                new.used = used;
                this.removeFromFreed(availBlock);
                used.not.if({ this.addToFreed(new) });
-               array[new.start] = new;
+               array[new.start - offset] = new;
                leftover.notNil.if({
-                       array[leftover.start] = leftover;
+                       array[leftover.start - offset] = leftover;
                        top = max(top, leftover.start);
                        (top > leftover.start).if({ this.addToFreed(leftover); 
                });
```

**Comment by jamshark70** [comment]
This diff appears to function correctly.

**Test code:**

```
a = ContiguousBlockAllocator(20, 0, 100);

a.debug;

b = a.alloc(2);  // 100, correct

a.debug;

c = a.alloc(2);  // 102, correct
d = a.alloc(3);  // 104, correct

a.free(c);

a.debug;

c = a.alloc(1);  // 102, correct

a.debug;
->
Array:
0: ContiguousBlock(100, 2, true)
2: ContiguousBlock(102, 1, true)
3: ContiguousBlock(103, 1, false)
4: ContiguousBlock(104, 3, true)
7: ContiguousBlock(107, 13, false)

Free sets:
1: IdentitySet[ ContiguousBlock(103, 1, false) ]
```

At the end, it is in the correct state: 2 reserved, 1 reserved, 1 free, 3 reserved, the rest free.

**Diff:**

```
From 087c8d2b89378197d09d0c015a8a389ef21a601a Mon Sep 17 00:00:00 2001
From: James Harkins <jamshark70@dewdrop-world.net>
Date: Sat, 17 Jun 2017 20:57:33 +0800
Subject: [PATCH] Classlib: Add 'offset' variable to ContiguousBlockAllocator

---
 SCClassLibrary/Common/Control/Engine.sc | 36 ++++++++++++++++-----------------
 1 file changed, 18 insertions(+), 18 deletions(-)

diff --git a/SCClassLibrary/Common/Control/Engine.sc b/SCClassLibrary/Common/Control/Engine.sc
index 9cc31af..0967460 100644
--- a/SCClassLibrary/Common/Control/Engine.sc
+++ b/SCClassLibrary/Common/Control/Engine.sc
@@ -195,11 +195,11 @@ ContiguousBlock {
 
 
 ContiguousBlockAllocator {
-	var	size, array, freed, pos, top;
+	var	size, array, freed, pos, top, offset;
 
-	*new { |size, pos = 0|
-		^super.newCopyArgs(size, Array.newClear(size).put(pos, ContiguousBlock(pos, size-pos)),
-			IdentityDictionary.new, pos, pos);
+	*new { |size, pos = 0, offset = 0|
+		^super.newCopyArgs(size, Array.newClear(size).put(pos, ContiguousBlock(pos + offset, size-pos)),
+			IdentityDictionary.new, pos + offset, pos + offset, offset);
 	}
 
 	alloc { |n = 1|
@@ -211,7 +211,7 @@ ContiguousBlockAllocator {
 
 	reserve { |address, size = 1, warn = true|
 		var	block, new;
-		((block = array[address] ?? { this.findNext(address) }).notNil and:
+		((block = array[address - offset] ?? { this.findNext(address) }).notNil and:
 				{ block.used and:
 				{ address + size > block.start } }).if({
 			warn.if({ "The block at (%, %) is already in use and cannot be reserved."
@@ -240,15 +240,15 @@ ContiguousBlockAllocator {
 			prev, next, temp;
 		// this 'if' prevents an error if a Buffer object is freed twice
 		if(address.isNil) { ^this };
-		((block = array[address]).notNil and: { block.used }).if({
+		((block = array[address - offset]).notNil and: { block.used }).if({
 			block.used = false;
 			this.addToFreed(block);
 			((prev = this.findPrevious(address)).notNil and: { prev.used.not }).if({
 				(temp = prev.join(block)).notNil.if({
 						// if block is the last one, reduce the top
 					(block.start == top).if({ top = temp.start });
-					array[temp.start] = temp;
-					array[block.start] = nil;
+					array[temp.start - offset] = temp;
+					array[block.start - offset] = nil;
 					this.removeFromFreed(prev).removeFromFreed(block);
 					(top > temp.start).if({ this.addToFreed(temp); });
 					block = temp;
@@ -258,8 +258,8 @@ ContiguousBlockAllocator {
 				(temp = next.join(block)).notNil.if({
 						// if next is the last one, reduce the top
 					(next.start == top).if({ top = temp.start });
-					array[temp.start] = temp;
-					array[next.start] = nil;
+					array[temp.start - offset] = temp;
+					array[next.start - offset] = nil;
 					this.removeFromFreed(next).removeFromFreed(block);
 					(top > temp.start).if({ this.addToFreed(temp); });
 				});
@@ -280,8 +280,8 @@ ContiguousBlockAllocator {
 			});
 		});
 
-		(top + n > size or: { array[top].used }).if({ ^nil });
-		^array[top]
+		(top + n - offset > size or: { array[top - offset].used }).if({ ^nil });
+		^array[top - offset]
 	}
 
 	addToFreed { |block|
@@ -297,18 +297,18 @@ ContiguousBlockAllocator {
 
 	findPrevious { |address|
 		forBy(address-1, pos, -1, { |i|
-			array[i].notNil.if({ ^array[i] });
+			array[i - offset].notNil.if({ ^array[i - offset] });
 		});
 		^nil
 	}
 
 	findNext { |address|
 		var	temp;
-		(temp = array[address]).notNil.if({
-			^array[temp.start + temp.size]
+		(temp = array[address - offset]).notNil.if({
+			^array[temp.start + temp.size - offset]
 		}, {
 			for(address+1, top, { |i|
-				array[i].notNil.if({ ^array[i] });
+				array[i - offset].notNil.if({ ^array[i - offset] });
 			});
 		});
 		^nil
@@ -333,9 +333,9 @@ ContiguousBlockAllocator {
 		new.used = used;
 		this.removeFromFreed(availBlock);
 		used.not.if({ this.addToFreed(new) });
-		array[new.start] = new;
+		array[new.start - offset] = new;
 		leftover.notNil.if({
-			array[leftover.start] = leftover;
+			array[leftover.start - offset] = leftover;
 			top = max(top, leftover.start);
 			(top > leftover.start).if({ this.addToFreed(leftover); });
 		});
-- 
1.9.1
```

**Comment by adcxyz** [comment]
@jamshark70 thanks for the fix! 
will include, and do more tests.
I think keeping both offsets is the clearest option:
- the roping-off for reserved sections as was is good to keep,
- the big addrOffset used for shifting by clientID * fullRange is for a separate purpose, 
so it is good that it is clearly separate in concept and implementation.

**Comment by jamshark70** [comment]
To be clear, my patch replaces the version currently in the topic branch.

I wrote `offset` in my version instead of `addrOffset`, but as far as I can see, it's functionally the same. (If you prefer the name `addrOffset`, I don't have any objection to changing it -- really, I was just working on it as a lark last night and didn't bother to look up the branch again.) I haven't removed any offsets. We still use `pos` for reserved IDs, and there's a separate variable for the client ID offset. That is, I'm not questioning the rationale for the new offset.

**Comment by LFSaw** [comment]
Hello, just curious, any updates on this? What's the status? Where can I test/contribute?

**Comment by adcxyz** [comment]
merged with scotts elegant response from server that sets clientid in most cases - i need a quiet few hours to finalize and submit as pr, will ask you for review then!

**Comment by LFSaw** [comment]
looking forward! :)

**Comment by adcxyz** [comment]
this has been fixed in #3178 and the following Server refactorings.

**Comment by brianlheim** [comment]
@adcxyz Should this ticket be closed then?

**Comment by adcxyz** [comment]
yes, had meant to close it!
