### ISSUE TITLE
Problem with sending data with SerialPort to arduino.

### ISSUE THREAD

**Issue by Arseniusz** [supercollider/supercollider#3134]
I trying to send data to arduino using SerialPort example without any positive result.

Executing p.put(n) has no effect at all, but if I use routine
```supercollider
(
r= Routine({
    inf.do{|i|
        p.put(i.fold(0, 100).linexp(0, 100, 1, 255).asInteger.postln);
        0.02.wait;
    };
}).play;
)
```
I got two or three messages and then SerialPort going to close with this message:

1
1
2
2
2
2
SerialPort /dev/ttyUSB0 was closed
SerialPort Cleanup
2
WARNING: SerialPort not open

Here is full sc code:

```supercollider
(
p = SerialPort(
    "/dev/ttyUSB0",    //edit to match your port. SerialPort.listDevices
    baudrate: 9600,    //check that baudrate is the same as in arduino sketch
    crtscts: true);
)

//send serial data - slow pulsating
(
r= Routine({
    inf.do{|i|
        p.put(i.fold(0, 100).linexp(0, 100, 1, 255).asInteger.postln);
        0.02.wait;
    };
}).play;
)

r.stop;
p.close;
```
Same behavior on Ubuntu 16.03 and Debian 9. and SuperCollider version 3.6.6

**Comment by brianlheim** [comment]
hey @Arseniusz - what OS are you using, and what's your SuperCollider version?

**Comment by brianlheim** [comment]
you may also want to cross-post this on the sc-users mailing list. there are a lot of people that use SC+Arduino there.

**Comment by Arseniusz** [comment]
@brianlheim Same behavior on Ubuntu 16.03 and Debian 9. and SuperCollider version 3.6.6

**Comment by brianlheim** [comment]
OK. There are a couple things that might be going wrong:
- this may be a problem that was fixed in a more recent version of SuperCollider (latest stable is 3.8)
- there may be an issue in your Arduino sketch
- you may have faulty hardware

I think you're going to have to do more testing to determine if any of these is causing the problem, for instance by using another program to send the data or sending different or less data. If you'd like, you could post the code of your Arduino sketch.

**Comment by Arseniusz** [comment]
@brianlheim 
Arduino (both patch and hardware) works fine. I tested this example:
```arduino
int incomingByte = 0;   // for incoming serial data

void setup() {
  Serial.begin(9600);     // opens serial port, sets data rate to 9600 bps
}

void loop() {
  if (Serial.available() > 0) {
    incomingByte = Serial.read();
    Serial.print("I received: ");
    Serial.println(incomingByte, DEC);
  }
}
```
With simple bash command `echo 0 > /dev/ttyUSB0` and all work as expected.

On SuperCollider 3.8 and 3.9dev same still exist.

**Comment by brianlheim** [comment]
I'm unable to recreate this on my setup – macOS 10.13 with a Teensy 3.2 – using your code. I think you should either continue testing to narrow down what the problem could be, or send something to sc-users, or both.

Another thing to check is what the board is printing before it fails. you can see this by adding a few lines to your main routine:

```supercollider
//send serial data - slow pulsating
(
r= Routine({
    inf.do{|i|
		var char;
		p.put(i.fold(0, 100).linexp(0, 100, 1, 255).asInteger.postln);
		while { char = p.next; char.notNil } { post(char.asAscii) };
		0.02.wait;
    };
}).play;
)
```

**Comment by LFSaw** [comment]
For tracking down why your code is not working, please provide us with a simplified version of your Arduino patch and the SuperCollider example code (As I already wrote in the FB thread). Best as a [gist](https://gist.github.com/) .

Also, please tell us about the used hardware (which Arduino, which Arduino version etc.).

Although crude, I doubt that it is caused by the Serial implementation in SC. It generally does what it should and many people are using it. 

Did you try to send the commands as a pre-defined list with a different program than sc3? E.g. [coolterm](http://freeware.the-meiers.org/#CoolTerm) offers batch file execution, on linux, I am sure there's something similar.

**Comment by Arseniusz** [comment]
Sorry for late comment. I am on countryside now slightly without any micro-controllers. I'll check next week.

**Comment by Arseniusz** [comment]
Looks like problem was in serial monitor of Arduino IDE, not in SC or Arduino itself.
