### ISSUE TITLE
If `sclang` is started as a `systemd` service without `-l`, it throws `boost::filesystem::filesystem_error`

### ISSUE THREAD

**Issue by giuliomoro** [supercollider/supercollider#4132]
Environment
-----------

* Your SuperCollider version: 3.10-beta, running on Bela, which means there are a number of commits to add a different audio backend, but changes are only made to the `server`. The `merge-base` is `571b399d83f9f705075c004080596212802c362d` . Configured with:
```
-DNOVA_SIMD=ON -DSSE=OFF -DSSE2=OFF -DINSTALL_HELP=OFF -DSC_QT=OFF -DSC_IDE=OFF -DSC_EL=OFF -DSC_ED=OFF -DSC_VIM=OFF -DSC_HIDAPI=OFF -DSUPERNOVA=OFF -DNO_AVAHI=ON -DENABLE_TESTSUITE=OFF -DAUDIOAPI=bela 
```
* Your operating system and version: Bela v0.3.6 (Debian Stretch, kernel 4.4.113)

Steps to reproduce (for bugs)
-----------------------------

- create a `systemd` service that starts `sclang`, e.g.:
  - create a file in `/lib/systemd/system/sclang.service` with the following content (possibly adjust the path to sclang to match your system):
```
[Unit]
Description=Run sclang
DefaultDependencies=no
After=network-pre.target
Conflicts=shutdown.target
Before=shutdown.target

[Service]
ExecStart=/usr/bin/stdbuf -oL -eL /usr/local/bin/sclang
Type=simple
Restart=always

[Install]
WantedBy=default.target
```
- start such service: `systemctl start sclang`
- monitor its output: `journalctl -u sclang`

Error message (for bugs)
------------------------

The service fails with the following error:
```
Oct 20 16:12:48 bela systemd[1]: Started Run sclang.
Oct 20 16:12:48 bela stdbuf[734]: terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
Oct 20 16:12:48 bela stdbuf[734]:   what():  boost::filesystem::create_directories: Invalid argument
Oct 20 16:12:48 bela systemd[1]: sclang.service: Main process exited, code=killed, status=6/ABRT
Oct 20 16:12:49 bela systemd[1]: sclang.service: Unit entered failed state.
Oct 20 16:12:49 bela systemd[1]: sclang.service: Failed with result 'signal'.
Oct 20 16:12:49 bela systemd[1]: sclang.service: Service hold-off time over, scheduling restart.
Oct 20 16:12:49 bela systemd[1]: Stopped Run sclang.
```

Expected Behavior
-----------------

It should work, just like it works when running simply `sclang` from the command line.

Current Behavior
----------------

A workaround is running `sclang -l /path/to/non/existing/file` instead of simply `sclang` and it will work. I would expect it to work without such workaround.

**Comment by brianlheim** [comment]
Hey @giuliomoro, thanks for the report. Do you have the complete error message? The message you posted is cut off on the right hand side.

I think I know what call is causing this, but having the error message itself would be really helpful for knowing what to do to fix it.

**Comment by giuliomoro** [comment]
sorry, fixed now.

**Comment by bgola** [comment]
hi, i was checking issues here on SC repository and this one might be related to the unit / service file.

If you don't specify the user in the unit file, systemd won't set the environment variables like $HOME and that might be the case where sclang is getting lost trying to find the default config dir ( https://github.com/supercollider/supercollider/blob/develop/common/SC_Filesystem_unix.cpp#L104 ) and trying to create it fails.

Try adding User=root or something to the unit file.

Using the -l switch works because when you specify it, the sclang doesn't try to create the config directories. ( https://github.com/supercollider/supercollider/blob/develop/lang/LangSource/SC_TerminalClient.cpp#L267 )

So I think this is more related to systemd than supercollider but there is a "better" way to get the current user's home dir which is using `getpwuid`.

if you think that makes sense I can open a PR :)

**Comment by colinbrogan** [comment]
Hi, my service file looks like the following:
`
[Unit]
Description=Start SuperCollider
After=auto_jack.service

[Service]
ExecStart=/usr/bin/stdbuf -oL -eL /usr/local/bin/sclang -l /home/pi/mycode.scd
Type=simple
Restart=always

[Install]
WantedBy=boot_sc.target
`
I am still getting the following error:
`
Nov 13 00:43:21 realtimepi stdbuf[796]: terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
Nov 13 00:43:21 realtimepi stdbuf[796]:   what():  assign: Operation not permitted
Nov 13 00:43:21 realtimepi systemd[1]: auto_sc.service: Main process exited, code=killed, status=6/ABRT
Nov 13 00:43:21 realtimepi systemd[1]: auto_sc.service: Unit entered failed state.
Nov 13 00:43:21 realtimepi systemd[1]: auto_sc.service: Failed with result 'signal'.
`
@bgola  I thought you were saying the -l option would avoid this error.

@giuliomoro   I see your makefile revision comment. Is there someway I can recompile stock Supercollider with that revision?

I am desperate for some kind of workaround. I really need to launch supercollider from systemd.

**Comment by giuliomoro** [comment]
the `-l` flag needs to be followed by the path to the library configuration file. Currently, my command to run at startup looks like this:
```
bash -c 'touch /tmp/sclang.yaml; rm -rf /tmp/sclangfifo && mkfifo /tmp/sclangfifo && sclang -l /tmp/sclang.yaml /path/to/file/I/want/to/run.scd <> /tmp/sclangfifo'
```

I have not yet tried @bgola's suggestion:

> Try adding User=root or something to the unit file.

My `sclang` is built from source from 3.10beta. You can find the binary in this deb package: https://github.com/giuliomoro/supercollider/releases/tag/3.10beta1-Bela  . Note that you wouldn't want to install the whole package, as the version of `scsynth` it contains only runs on Bela, but `sclang` has no changes from the upstream supercollider.

**Comment by bgola** [comment]
@colinbrogan the error you are observing is different from the one @giuliomoro is reporting here.

i tried it on my system (archlinux with the develop version of supercollider) and couldn't reproduce.

maybe you could open a new issue with more details (your system, version of supercollider, complete log, etc)? :)

**Comment by brianlheim** [comment]
See also disc in #4132. Closing as user error

**Comment by jreus** [comment]
I'm trying to move my bela_startup.service into the user domain due to being unable to resolve "~".absolutePath when running a SuperCollider program on Bela bootup. 

However, after moving the service file to my userspace directory I'm getting the error `Failed to connect to bus: No such file or directory`

```
root@bela:~# mkdir ~/.config/systemd/user
root@bela:~# cp /lib/systemd/system/bela_startup.service ~/.config/systemd/user/
root@bela:~# systemctl disable bela_startup
root@bela:~# systemctl --user enable bela_startup
Failed to connect to bus: No such file or directory
```

@dvzrv maybe you have some idea how to overcome this issue?

> @giuliomoro why do you want to start this as a system service? sclang doesn't require root privileges to function!
> What you probably actually want is a user service, that starts sclang (you can place it below `~/.config/systemd/user/` for testing and convenience). You can then start/enable that service like any other user service (`systemctl --user start my.service`/ `systemctl --user enable my.service`) to make it start with that user's session. If that user's session should start when the system starts, enable linger for it (`loginctl enable-linger`).
> 
> @bgola Adding `User=root` to the service file does absolutely nothing in the case of a system service (they are run as root by default). However, you could specify a system service with a specific user of course (`User=myuser`). Due to requiring root to edit those service files I wouldn't recommend it though (especially not for testing purposes).

**Comment by dvzrv** [comment]
@jreus You need to start that service as the user that is supposed to run the service, not as root.

In your case: Create an unprivileged user (e.g. `foo`) and copy the service to that user's systemd config dir (e.g. `/home/foo/.config/systemd/user/`).
Then start that service (as the user `foo` -- not as root!): `systemctl --user start bela_startup`

Background: When doing all of this as root you would also run the "user service" as root (which defies the purpose). However, root is not a user in that sense and does not represent "a real person".
This fact is also reflected in the system and user services for dbus:

```
# /usr/lib/systemd/system/dbus.service
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket

[Service]
ExecStart=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ExecReload=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
OOMScoreAdjust=-900
```

```
# /usr/lib/systemd/user/dbus.service
[Unit]
Description=D-Bus User Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket

[Service]
ExecStart=/usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ExecReload=/usr/bin/dbus-send --print-reply --session --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
```

While a common "user" would log in and have a session, root does not have a session dbus attached to itself.
It's probably best to think of root never as a user, but only as a tool to administrate one's system.

**Comment by giuliomoro** [comment]
Thanks for your response. I guess the problem is that on the Bela image there is only one user: `root`. This is because one needs to have root privileges in order to run a process that uses Xenomai (the real-time co-kernel we use), and avoiding to `sudo` everything simplified the management of the image. I think a good workaround for the issue above is to run it as a `system` service, specifying `User=root` (under `[Service]`), which will set the `$HOME` environment variable appropriately, so that Sc's tilde resolution works as expected.

**Comment by jreus** [comment]
I've tried @giuliomoro 's solution and it solves the user dir resolution issue
namely, editing `/lib/systemd/system/bela_startup.service`
to include
```
[Service]
User=root
```


> Thanks for your response. I guess the problem is that on the Bela image there is only one user: `root`. This is because one needs to have root privileges in order to run a process that uses Xenomai (the real-time co-kernel we use), and avoiding to `sudo` everything simplified the management of the image. I think a good workaround for the issue above is to run it as a `system` service, specifying `User=root` (under `[Service]`), which will set the `$HOME` environment variable appropriately, so that Sc's tilde resolution works as expected.
